name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "apps/docs/**"
      - "packages/config/**"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "apps/docs/**"
      - "packages/config/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "pnpm"

      - name: Setup Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint docs
        run: pnpm docs:lint

      - name: Type check docs
        run: pnpm docs:type-check

      - name: Format check docs
        run: pnpm docs:format:check

      - name: Build docs
        run: pnpm docs:build
        env:
          NODE_ENV: production

      - name: Verify build output
        run: |
          echo "Checking if out directory exists..."
          ls -la apps/docs/
          echo "Checking out directory contents..."
          ls -la apps/docs/out/ || echo "out directory not found"

      - name: Upload Pages Artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./apps/docs/out"
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
